version: '3.2'

services:
    database:
        build:
            context: ./docker/mysql
        working_dir: /srv
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - database:/var/lib/mysql
        ports:
            - "8306:3306"

    php:
        build:
            context: ./docker/php
        working_dir: /srv
        volumes:
            - ./:/srv/

    api-quizz.troopers.agency:
        image: nginx:1-alpine
        depends_on:
            - php
        volumes:
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public/:/srv/public/:delegated
        ports:
            - "8000:80"

    selenium:
        image: selenium/standalone-chrome:2.53.1
        expose:
            - "4444"
        volumes:
            - /dev/shm:/dev/shm
            - ./:/srv/

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"

volumes:
    database: ~
